import React from "react";
import { useState } from "react";
import { Container, Row, Col, Button, Form } from "react-bootstrap";
import { FaCheck } from "react-icons/fa";

const featuresData = [
{ "title": "Examination Management" },
{ "title": "HR & Payroll" },
{ "title": "Fee Management" },
{ "title": "CRM integration" },
{ "title": "Attendance management" },
{ "title": "Academics" },
{ "title": "Financial Management" },
{ "title": "Activities" },
{ "title": "Accounting" },
{ "title": "Event Calendar" },
{ "title": "Event Management" },
{ "title": "Customer Management" },
{ "title": "Help Desk" },
{ "title": "Admission" },
{ "title": "Email Integration" },
{ "title": "Employee Self Service Management" },
{ "title": "Database backup/restore (Management)" },
{ "title": "CRM" },
{ "title": "Hostel Management" },
{ "title": "Kiosk System" },
{ "title": "Courses and Batches Management" },
{ "title": "Expense Tracking" },
{ "title": "Inventory Management" },
{ "title": "Document Management" }
];

const moreFeatures = [
  { "title": "Travel Management" },
  { "title": "Reception & Front Office" },
  { "title": "Student Info Management" },
  { "title": "Online Tests & Psychometric Tests" },
  { "title": "Catalog Management" },
  { "title": "Time Table" },
  { "title": "Library Management" },
  { "title": "Training Management" },
  { "title": "Project Management" },
  { "title": "Knowledge Management" },
  { "title": "Registration Management" },
  { "title": "Survey Management" },
  { "title": "Mass Email" },
  { "title": "Mobile App" },
  { "title": "Time & Attendance Management" },
  { "title": "User Customisation" },
  { "title": "Multiuser Login & Role-based access control" },
  { "title": "Payment Gateway Integration" },
  { "title": "Payroll Management" },
  { "title": "Transport / Fleet Management" },
  { "title": "Time Tracking" },
  { "title": "Shift Management" },
  { "title": "SMS" },
  { "title": "Mobile Support" },
  { "title": "General Ledger" },
  { "title": "Contact Management" },
  { "title": "Timesheet Management" },
  { "title": "Fund accounting" },
  { "title": "Collaboration Tools" },
  { "title": "Accounts payable" },
  { "title": "Onboarding" },
  { "title": "Electronic Signature" },
  { "title": "Applicant tracking" },
  { "title": "API Integration" },
  { "title": "Recruiting Management" },
  { "title": "Fundraising Management" },
  { "title": "Compliance Management" },
  { "title": "Employee Management" },
  { "title": "Interview Management" },
  { "title": "Leave Management" },
  { "title": "Invoices" },
  { "title": "Payroll Integration" },
  { "title": "Franchise Management" },
  { "title": "Absence Management" },
  { "title": "Applications Management" },
  { "title": "Data Security" },
  { "title": "Membership Management" },
  { "title": "Assessments" },
  { "title": "Self Service Portal" },
  { "title": "Barcode Scanning" },
  { "title": "Dispatching" },
  { "title": "FMLA Tracking" },
  { "title": "Candidate Management" },
  { "title": "Accounting Integration" },
  { "title": "Multi-Location" },
  { "title": "Workflow Management" },
  { "title": "Collaboration" },
  { "title": "Overtime Tracking" },
  { "title": "Employee Scheduling" },
  { "title": "Idea Management" },
  { "title": "Application Integration" },
  { "title": "Work order management" },
  { "title": "User Management" },
  { "title": "SMS Integration" },
  { "title": "Dispatching" },
  { "title": "Payroll Integration" },
  { "title": "Resource Management" },
  { "title": "Billing & Invoicing" },
  { "title": "Payment Processing" },
  { "title": "Residential Properties" },
  { "title": "Acquisition Management" },
  { "title": "Barcoding / RFID" },
  { "title": "Circulation Management" },
  { "title": "Fee Collection" },
  { "title": "OPAC" },
  { "title": "Patron Management" },
  { "title": "Periodicals Management" },
  { "title": "Reserve Shelf Management" },
  { "title": "Search Functionality" },
  { "title": "Self Check-in / Check-Out" },
  { "title": "Serials Management" },
  { "title": "Kiosk Integration" },
  { "title": "Unicode Compliance" },
  { "title": "Feedback Management" },
  { "title": "Goal Management" },
  { "title": "Goal Setting / Tracking" },
  { "title": "Surveys & Feedback" },
  { "title": "Ad hoc Analysis" },
  { "title": "Ad Hoc Reports" },
  { "title": "Budgeting & Forecasting" },
  { "title": "Consolidation / Roll-Up" },
  { "title": "Key Performance Indicators" },
  { "title": "Qualitative Analysis" },
  { "title": "Quantitative Analysis" },
  { "title": "Strategic Planning" },
  { "title": "Campaign Management" },
  { "title": "Admissions Management" },
  { "title": "Mass Texting" },
  { "title": "Polls / Voting" },
  { "title": "Scheduling" },
  { "title": "Approval Process Control" },
  { "title": "Rich Text Editor" },
  { "title": "Contract Management" },
  { "title": "Calendar Management" },
  { "title": "Role-Based Permissions" },
  { "title": "Mileage Tracking" },
  { "title": "Vehicle Tracking" },
  { "title": "Purchasing" },
  { "title": "Forms Management" },
  { "title": "Customizable Reporting" },
  { "title": "Integrate Different Payment Gateways" },
  { "title": "Online Results Declaration" },
  { "title": "Student Assessment Reports" },
  { "title": "Grading Assessment System Integration" },
  { "title": "Admission Receipt Generation" },
  { "title": "Multi-Located Branched Integration" },
  { "title": "Job Category Management" },
  { "title": "E-library Members Management" },
  { "title": "Biometric Attendance Management" },
  { "title": "Laboratory Management" },
  { "title": "Course Management" },
  { "title": "Student Evaluation Report" },
  { "title": "Lecture Management" },
  { "title": "Faculty Management" },
  { "title": "Staff Management" },
  { "title": "Data Management" },
  { "title": "Reporting" },
  { "title": "Purchase Management" },
  { "title": "School Management" },
  { "title": "College Management" },
  { "title": "HRM" },
  { "title": "Accessibility" },
  { "title": "Time Reminder" },
  { "title": "Result Release" },
  { "title": "Generate Reports" },
  { "title": "Customizable Workflows" },
  { "title": "Automatic Grading" },
  { "title": "Certification" },
  { "title": "Paper Tests" },
  { "title": "Question Bank" },
  { "title": "Quizzes" },
  { "title": "Employee Training" },
  { "title": "Student Manage" },
  { "title": "Client Management" },
  { "title": "Marketing Management" },
  { "title": "Overtime Management" },
  { "title": "Mailing list management" },
  { "title": "Roadmapping" },
  { "title": "Customization" },
  { "title": "Attendee Management" },
  { "title": "Badge Management" },
  { "title": "Member Portal" },
  { "title": "Facility Scheduling" },
  { "title": "Assessment Management" },
  { "title": "Attendance Tracking" },
  { "title": "Behavior Management" },
  { "title": "Bookstore Management" },
  { "title": "Cafeteria Management" },
  { "title": "Classroom Management" },
  { "title": "Clinic Management" },
  { "title": "Curriculum Management" },
  { "title": "Enrollment Management" },
  { "title": "Facility Management" },
  { "title": "Higher Education" },
  { "title": "Housing Management" },
  { "title": "Independent / Private" },
  { "title": "K-12" },
  { "title": "Parent Portal" },
  { "title": "School District" },
  { "title": "Special Education" },
  { "title": "Student Information / Records" },
  { "title": "Student Portal" },
  { "title": "Question Branching" },
  { "title": "Question Randomizing" },
  { "title": "Results Reporting" },
  { "title": "Weighted Questions" },
  { "title": "Wait List Management" },
  { "title": "Competency Tracking" },
  { "title": "Individual Development Plans" },
  { "title": "Maintenance Management" },
  { "title": "Succession Planning" },
  { "title": "Communication Management" },
  { "title": "Scorecarding" },
  { "title": "Progress Tracking" },
  { "title": "Multi-User Collaboration" },
  { "title": "Employee Tracking" },
  { "title": "Time Management" },
  { "title": "Fixed Asset Management" },
  { "title": "Internet Usage Monitoring" },
  { "title": "Materials Management" },
  { "title": "Member Directory" },
  { "title": "Pledge Management" },
  { "title": "Volunteer Management" },
  { "title": "Group Management" },
  { "title": "Audio / Video Conferencing" },
  { "title": "Brainstorming" },
  { "title": "Discussion Boards" },
  { "title": "Class Management" },
  { "title": "Asynchronous Learning" },
  { "title": "Built-In Course Authoring" },
  { "title": "Certification Management" },
  { "title": "Corporate / Business" },
  { "title": "Gradebook" },
  { "title": "Live / Video Conferencing" },
  { "title": "Skills Tracking" },
  { "title": "Social Learning" },
  { "title": "Training Companies" },
  { "title": "Synchronous Learning" },
  { "title": "eCommerce" },
  { "title": "Blended Learning" },
  { "title": "Appointment Scheduling" },
  { "title": "Overtime Calculation" },
  { "title": "Online payments" },
  { "title": "GPS tracking" },
  { "title": "Email Marketing" },
  { "title": "Reporting & Statistics" },
  { "title": "Competency Management" },
  { "title": "Fees" },
  { "title": "Automated Scheduling" },
  { "title": "Group Scheduling" },
  { "title": "Donation Tracking" },
  { "title": "Donor Database" },
  { "title": "Gift Management" },
  { "title": "Mobile Donations" },
  { "title": "Online Donations" },
  { "title": "Recurring Donations" },
  { "title": "Receipts / Statements" },
  { "title": "Donor Management" },
  { "title": "Alumni Management" },
  { "title": "Contribution Tracking" },
  { "title": "Recurring Giving" },
  { "title": "Committee Management" },
  { "title": "Member Database" },
  { "title": "Approval Process Management" },
  { "title": "Minutes Management" },
  { "title": "Student Management" },
  { "title": "Daily Reports" },
  { "title": "Parent App" },
  { "title": "Teacher App" },
  { "title": "School branded App" },
  { "title": "School Bus Attendance" },
  { "title": "Customized Report Cards" },
  { "title": "Parents’ Survey" },
  { "title": "Admission CRM" },
  { "title": "Online Assessment" },
  { "title": "Room Scheduling" },
  { "title": "Space Planning" },
  { "title": "Auto-Formatting Manuscripts" },
  { "title": "Re-Formatting Manuscripts" },
  { "title": "Equation Editor" },
  { "title": "Customisable Sections" },
  { "title": "Tables" },
  { "title": "Automatic Citation Numbering" },
  { "title": "Suggestions" },
  { "title": "Download in PDF" },
  { "title": "DOCX" },
  { "title": "LaTeX" },
  { "title": "Import references" },
  { "title": "Journal Formats" },
  { "title": "Automated Shift Scheduling" },
  { "title": "Centralized Monitoring" },
  { "title": "Reporting/Analytics" },
  { "title": "Class Scheduling" },
  { "title": "Real-time Scheduling" },
  { "title": "Resource Scheduling" },
  { "title": "Analytics & Reporting" },
  { "title": "Content Management" },
  { "title": "Feedback System" },
  { "title": "Contextual Speller" },
  { "title": "Dictionary / Thesaurus" },
  { "title": "Grammar Check" },
  { "title": "Plagiarism Detection" },
  { "title": "Punctuation Check" },
  { "title": "Spell Check" },
  { "title": "Style Check" },
  { "title": "Scenario Planning" },
  { "title": "Test / Quiz Creation" },
  { "title": "Gamification" },
  { "title": "Live Tutorials" },
  { "title": "Reviewer Portal" },
  { "title": "Self Assessment" },
  { "title": "User Access Permissions" },
  { "title": "HR Management" },
  { "title": "Barcoding/RFID" },
  { "title": "Menu Planning" },
  { "title": "Academic/Education" },
  { "title": "Corporate/Business" },
  { "title": "Check-in / Check-out" },
  { "title": "Online Calendar" },
  { "title": "Engagement Monitoring" },
  { "title": "Scoring" },
  { "title": "Skill Testing" },
  { "title": "Program Management" },
  { "title": "Orientation Management" },
  { "title": "Agenda Management" },
  { "title": "Internal Meetings" },
  { "title": "Meeting Preparation Tools" },
  { "title": "Post-Meeting Tools" },
  { "title": "Individualized Assessments" },
  { "title": "Skills Assessments" },
  { "title": "Colleges / Universities" },
  { "title": "Evaluation Management" },
  { "title": "Faculty / Staff Management" },
  { "title": "Financial Aid Management" },
  { "title": "Surveys" },
  { "title": "Leave & Absence Reporting" },
  { "title": "Commenting / Notes" },
  { "title": "Volunteer Profiles" },
  { "title": "Member Communities" },
  { "title": "Expiration Management" },
  { "title": "Learner Portal" },
  { "title": "Video Conferencing" },
  { "title": "Real-time Chat" },
  { "title": "Text Messaging" },
  { "title": "Form Builder" },
  { "title": "Online Registration" },
  { "title": "KPIs" },
  { "title": "Scorecards" },
  { "title": "Aggregate Reports" },
  { "title": "Group Summary Report" },
  { "title": "Individual Reports" },
  { "title": "Rater Tracking" },
  { "title": "Online Applications" },
  { "title": "Photo Gallery" },
  { "title": "Leave Policy Management" },
  { "title": "Grant Award Tracking" },
  { "title": "Grant Opportunity Search" },
  { "title": "Learning Plans" },
  { "title": "Member Accounts" },
  { "title": "For Classroom" },
  { "title": "Remote Access/Control" },
  { "title": "Support Audio/Images/Video" },
  { "title": "Tests/Assessments" },
  { "title": "Transcripts" },
  { "title": "Media Management" },
  { "title": "Testing / Assessments" },
  { "title": "Virtual Classroom" },
  { "title": "Progress Reports" },
  { "title": "Confirmation/Reminders" },
  { "title": "Discount/Coupon Management" },
  { "title": "Activity Registration" },
  { "title": "Class Registration" },
  { "title": "Event Registration" },
  { "title": "Group Registration" },
  { "title": "Onsite Registration" },
  { "title": "Refund Automation" },
  { "title": "Report Cards" },
  { "title": "Class Summary" },
  { "title": "Parent/Student Portal" },
  { "title": "Independent/Private" },
  { "title": "Electronic Assignments & Tests" },
  { "title": "Built in LMS" },
  { "title": "Curve Scores" },
  { "title": "Field Reporting" },
  { "title": "Lesson Notes" },
  { "title": "Taxation & Assessment" },
  { "title": "Grade Calculations" },
  { "title": "Customizable Forms" },
  { "title": "Lesson Planning" },
  { "title": "Incident Mapping" },
  { "title": "Medical Management" },
  { "title": "Lesson Plan Management" },
  { "title": "Applicant Portal" },
  { "title": "Board Meetings" },
  { "title": "Instructor Management" },
  { "title": "Voting Management" },
  { "title": "Communication Tools" },
  { "title": "Certification Tracking" },
  { "title": "Lesson Plan Management" },
  { "title": "Committee Meetings" },
  { "title": "Applicant Management" },
  { "title": "Public Libraries" },
  { "title": "Recognition Management" },
  { "title": "Church Libraries" },
  { "title": "Lesson Notes" },
  { "title": "View Student Monitors" },
  { "title": "Self Check-in/Check-out" },
  { "title": "Food Service Management" },
  { "title": "Weighted Assignments" },
  { "title": "Business Coaching" },
  { "title": "Mentor/Coach Matching" },
  { "title": "Interactive Learning" },
  { "title": "Parent / Child Records" },
  { "title": "School Libraries" },
  { "title": "Life Coaching" },
  { "title": "Law Libraries" },
  { "title": "Immunization Records" },
  { "title": "Private Libraries" },
  { "title": "Class Loading" },
  { "title": "Dispatch Monitoring" },
  { "title": "Public Libraries" },
  { "title": "Food Program Records" },
  { "title": "Self Check-in/Check-out" },
  { "title": "Church Libraries" },
  { "title": "Immunization Records" },
  { "title": "Private Libraries" },
  { "title": "Class Loading" },
  { "title": "Dispatch Monitoring" },
  { "title": "Public Libraries" },
  { "title": "Food Program Records" },
  { "title": "Facial Recognition Attendance" },
  { "title": "Online Classes" },
  { "title": "Group Attendance" },
  { "title": "Employee Hourly Wages" },
  { "title": "Centralized Finance Manager" },
  { "title": "Live Class Enablement" },
  { "title": "Insightful Statistics" },
  { "title": "Student Group Management" },
  { "title": "White Label" },
  { "title": "Sport Coaching" },
  { "title": "Shift Planner" },
  { "title": "Practice Test Question Bank" },
  { "title": "Recommendations Management" },
  { "title": "Geofencing Time And Attendance" },
  { "title": "Automatic Test Creation & Grading" },
  { "title": "Upcoming Batches" },
  { "title": "Deviceless GPS Tracking" },
  { "title": "Admin Controls" },
  { "title": "Parent Communication" },
  { "title": "Expense Manager" },
  { "title": "Reviewer Management" },
  { "title": "Exam Planner" },
  { "title": "Dedicated Support Manager" },
  { "title": "Attendance Reporting" },
  { "title": "Computer Based Test" },
  { "title": "Insightful Statistics" },
  { "title": "Parent Communication" },
  { "title": "Exam Planner" },
  { "title": "Dedicated Support Manager" },
  { "title": "Attendance Reporting" },
  { "title": "Computer Based Test" },
  { "title": "Insightful Statistics" }
];
const Features = ({ styles }) => {
  const [isShowMore, setIsShowMore] = useState(false);
  const toggleReadMoreLess = () => {
    setIsShowMore(!isShowMore);
  };

  const [searchQuery, setSearchQuery] = useState("");

  const handleSearch = (e) => {
    setSearchQuery(e.target.value);
  };

  const combinedFeatures = [...featuresData, ...moreFeatures];
  const filteredFeatures = combinedFeatures.filter((feature) =>
    feature.title.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const displayFeatures = searchQuery
    ? filteredFeatures
    : isShowMore
    ? combinedFeatures
    : featuresData;
  return (
    <>
      <Container>
          <Row>
            <Col lg={12}>
              <h3 className="mb-4">Key Features</h3>
              <Form>
              <Form.Group>
            <Form.Control
              type="text"
              placeholder="Search Features..."
              value={searchQuery}
              onChange={handleSearch}
              className="mb-4"
            />
            </Form.Group>
            </Form>
            </Col>
            {displayFeatures.length > 0 ? (
          displayFeatures.map((feature, index) => (
            <Col lg={3} className="mb-4" key={index}>
              <div className="box h-100 shadow border rounded-4 p-4 bg-light">
                {" "}
                <h5>
                  <span style={{ color: "#f95738 " }}>
                    <FaCheck />
                  </span>
                  &nbsp; {feature.title}
                </h5>
              </div>
            </Col>
          ))
        ) : (
          <div className="box shadow border rounded-4 p-4 bg-light text-center">
                <h5>No records found</h5>
              </div>
        )}
          {/* {isShowMore && 
          <>
          {filteredMoreFeatures.map((featureM, index) => (
            <Col lg={3} className="mb-4" key={index}>
              <div className="box h-100 shadow border rounded-4 p-4 bg-light">
                {" "}
                <h5>
                  <span style={{ color: "#f95738 " }}>
                    <FaCheck />
                  </span>
                  &nbsp; {featureM.title}
                </h5>
              </div>
            </Col>
          ))}
          </>
          } */}
          {!searchQuery && (
          <Col lg={12}>
            <div className={styles["feature-btn"]}>
              <Button className="mt-4" onClick={toggleReadMoreLess}>
                {isShowMore ? "Show Less \u2191" : "Show More \u2193"}
              </Button>
            </div>
          </Col>
           )}
          </Row>
      </Container>
    </>
  );
};

export default Features;
