import React from "react";
import { Container, Row, Col } from "react-bootstrap";

const uspData = [
  {
    "title": "Proven Track Record",
    "content": "The CRM software has <span style=\"color:#FC5185 ;\"><strong>15+ years</strong></span> of experience in the sales CRM industry. Trusted by over <span style=\"color:#FC5185 ;\"><strong>1,00,000</strong></span> users and loved by <span style=\"color:#FC5185 ;\"><strong>1000+</strong></span> companies in India."
  },
  {
    "title": "Lead Automation & Distribution",
    "content": "Effortlessly captures, categorizes, and routes leads to the right sales reps instantly. Boosts sales team response time, ensuring no sales lead is missed. Seamlessly integrated with various platforms such as Google, Facebook, Email, Websites, and more."
  },
  {
    "title": "Android GSM SIM-Based Built-in Dialer",
    "content": "Allows users to make calls to leads and customers effortlessly using the built-in phone dialer. Enables easy update of call status, addition of notes, and scheduling of sales follow-ups."
  },
  {
    "title": "WhatsApp Marketing Automation",
    "content": "Facilitates sending offers, discount coupons, and festive greetings via WhatsApp without risking number blocking. Automates welcoming new leads via WhatsApp with sales brochures, intro videos, or PPT attachments."
  },
  {
    "title": "Track Performance & Drive Sales Actions",
    "content": "Monitors open leads at every pipeline stage, tracks revenue generated by sales reps, teams, regions, etc. Utilizes over 100+ reports and customizable dashboards for comprehensive performance measurement."
  },
  {
    "title": "Industry-Specific Customization",
    "content": "Tailored CRM solutions for various industries, including B2B companies, real estate, financial services, education, tours & travel, recruitment, professional services, and others."
  }
];
{/* <span style=\"color:#FC5185 ;\"><strong> */}
const renderHTML = (rawHTML) => {
  return React.createElement("p", {
    dangerouslySetInnerHTML: { __html: rawHTML },
  });
};

const Usp = ({ styles }) => {
  return (
    <>
      <Container>
        <Row>
          <Col lg={12}>
            <h3 className="mb-3">USP of Cratio CRM</h3>
          </Col>
          {uspData.map((item, index) => (
            <Col lg={4} className="mb-4" key={index}>
              <div
                className={`${styles["box-bgclr"]} box h-100 p-4 rounded-4 border text-center`}
              >
                <h5>{item.title}</h5>
                <br />
                {/* <p dangerouslySetInnerHTML={{ __html: item.content }} /> */}
                {renderHTML(item.content)}
              </div>
            </Col>
          ))}
        </Row>
      </Container>
    </>
  );
};

export default Usp;
